import { Patient } from './types';

export const Patients: Patient[] = [
  {
    name: 'Akida Juma',
    gender: 'Male',
    age: 24,
    hospital: 'Inguinal Mesh Hernia',
    patientHospitalId: '596886',
    id: '1928394',
  },
  {
    name: 'Darweshi Mohamed',
    gender: 'Female',
    age: 88,
    hospital: 'Inguinal Mesh Hernia',
    patientHospitalId: '849305',
    id: '1928495',
  },
  {
    name: 'Zuwena Juma',
    gender: 'Male',
    age: 32,
    hospital: 'Inguinal Mesh Hernia',
    patientHospitalId: '172894',
    id: '2930221',
  },
  {
    name: 'Akida Ramadhani',
    gender: 'Female',
    age: 1,
    hospital: 'Inguinal Mesh Hernia',
    patientHospitalId: '957489',
    id: '1985748',
  },
  {
    name: 'Sekelaga Juma',
    gender: 'Female',
    age: 23,
    hospital: 'Inguinal Mesh Hernia',
    patientHospitalId: '109872',
    id: '2948394',
  },
  {
    name: 'Kanoni Ramadhani',
    gender: 'Male',
    age: 89,
    hospital: 'Inguinal Mesh Hernia',
    patientHospitalId: '285940',
    id: '2993456',
  },
  {
    name: 'Baraka Mohamed',
    gender: 'Male',
    age: 102,
    hospital: 'Inguinal Mesh Hernia',
    patientHospitalId: '884493',
    id: '9993456',
  },
  {
    name: 'Fadhila Juma',
    gender: 'Female',
    age: 76,
    hospital: 'Inguinal Mesh Hernia',
    patientHospitalId: '992345',
    id: '1829304',
  },
  {
    name: 'Magreth Hamad',
    gender: 'Female',
    age: 54,
    hospital: 'Inguinal Mesh Hernia',
    patientHospitalId: '129845',
    id: '2944839',
  },
  {
    name: 'Fadhila Ramadhani',
    gender: 'Male',
    age: 12,
    hospital: 'Inguinal Mesh Hernia',
    patientHospitalId: '284932',
    id: '1111945',
  },
  {
    name: 'Abdul Juma',
    gender: 'Male',
    age: 19,
    hospital: 'Inguinal Mesh Hernia',
    patientHospitalId: '192859',
    id: '1000456',
  },
];
